### ISSUE TITLE
Eror in Unix 

### ISSUE THREAD

**Issue by attar110** [sobhe/hazm#132]
I install HAZM In ubonto but it haz following Eror     WHAT SHOULD I DO PLEASE Guide ME!!!!!!!!!!!!!!!!

Failed building wheel for libwapiti
Running setup.py clean for libwapiti
Failed to build libwapiti

unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by nournia** [comment]
Hi,
You should install python-dev for compiling libwapiti:

    sudo apt install python-dev

**Comment by mojtabavasou** [comment]
I tried to install HAZM, but there is a problem to build wheel for libwapiti(setup.py). OS is ubuntu 18 and python which I use is 3.8. does any body know that how to fix it?

> pip3 install hazm
Defaulting to user installation because normal site-packages is not writeable
Collecting hazm
  Using cached hazm-0.7.0-py3-none-any.whl (316 kB)
Requirement already satisfied: nltk==3.3 in ./.local/lib/python3.8/site-packages (from hazm) (3.3)
Collecting libwapiti>=0.2.1
  Using cached libwapiti-0.2.1.tar.gz (233 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from nltk==3.3->hazm) (1.14.0)
Building wheels for collected packages: libwapiti
  Building wheel for libwapiti (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b49uh3c0
       cwd: /tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/wapiti
  copying wapiti/script.py -> build/lib.linux-x86_64-3.8/wapiti
  copying wapiti/api.py -> build/lib.linux-x86_64-3.8/wapiti
  copying wapiti/__init__.py -> build/lib.linux-x86_64-3.8/wapiti
  running egg_info
  writing libwapiti.egg-info/PKG-INFO
  writing dependency_links to libwapiti.egg-info/dependency_links.txt
  writing requirements to libwapiti.egg-info/requires.txt
  writing top-level names to libwapiti.egg-info/top_level.txt
  reading manifest file 'libwapiti.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'libwapiti.egg-info/SOURCES.txt'
  running build_ext
  building 'libwapiti' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/cwapiti
  creating build/temp.linux-x86_64-3.8/cwapiti/src
  creating build/temp.linux-x86_64-3.8/libwapiti
  creating build/temp.linux-x86_64-3.8/libwapiti/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Icwapiti/src -Ilibwapiti -I/usr/include/python3.8 -c cwapiti/src/pattern.c -o build/temp.linux-x86_64-3.8/cwapiti/src/pattern.o -std=c99
  cwapiti/src/pattern.c:28:10: fatal error: ctype.h: No such file or directory
     28 | #include <ctype.h>
        |          ^~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for libwapiti
  Running setup.py clean for libwapiti
Failed to build libwapiti
Installing collected packages: libwapiti, hazm
    Running setup.py install for libwapiti ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w5rcs1_b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jacke/.local/include/python3.8/libwapiti
         cwd: /tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/wapiti
    copying wapiti/script.py -> build/lib.linux-x86_64-3.8/wapiti
    copying wapiti/api.py -> build/lib.linux-x86_64-3.8/wapiti
    copying wapiti/__init__.py -> build/lib.linux-x86_64-3.8/wapiti
    running egg_info
    writing libwapiti.egg-info/PKG-INFO
    writing dependency_links to libwapiti.egg-info/dependency_links.txt
    writing requirements to libwapiti.egg-info/requires.txt
    writing top-level names to libwapiti.egg-info/top_level.txt
    reading manifest file 'libwapiti.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'libwapiti.egg-info/SOURCES.txt'
    running build_ext
    building 'libwapiti' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/cwapiti
    creating build/temp.linux-x86_64-3.8/cwapiti/src
    creating build/temp.linux-x86_64-3.8/libwapiti
    creating build/temp.linux-x86_64-3.8/libwapiti/src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Icwapiti/src -Ilibwapiti -I/usr/include/python3.8 -c cwapiti/src/pattern.c -o build/temp.linux-x86_64-3.8/cwapiti/src/pattern.o -std=c99
    cwapiti/src/pattern.c:28:10: fatal error: ctype.h: No such file or directory
       28 | #include <ctype.h>
          |          ^~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ib11vgjm/libwapiti_aaf0ff842d234db18616e92900881037/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w5rcs1_b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jacke/.local/include/python3.8/libwapiti Check the logs for full command output.
jacke@ubuntu:~$ 

>

**Comment by nournia** [comment]
Hi,
Here you can see the installation procedure on python 3.8:

https://travis-ci.org/github/sobhe/hazm/jobs/754862228

**Comment by atefe-gh** [comment]
Hi,
I install HAZM In wsl but it has following Error:
I also installed python-dev for compiling libwapiti

Failed building wheel for libwapiti
Running setup.py clean for libwapiti
Failed to build libwapiti

unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
